SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE dbo.sp_Quotes_DeleteLinesByQuote
    @QuoteId INT
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM dbo.QuoteLineItems
    WHERE QuoteId = @QuoteId;

    SELECT @@ROWCOUNT AS RowsAffected;
END
GO
