-- =====================================================================
-- ManageR2 PostgreSQL schema - Core identity domain (Waves 1-2)
-- Translated from database/schema/tables.sql (SQL Server baseline).
-- Apply order within this file respects FK dependencies:
--   Employees, Roles, Departments, Users, UserRoles, UserDepartments, CompanySettings
-- Identifiers preserve PascalCase (double-quoted) to match SQL Server column names.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Employees
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Employees" (
    "EmployeeId"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FullName"           varchar(100) NOT NULL,
    "PrimaryRole"        varchar(100) NOT NULL,
    "Phone"              varchar(20)  NULL,
    "Email"              varchar(100) NULL,
    "IsActive"           boolean NOT NULL DEFAULT true,
    "CreatedAt"          timestamp(6) NOT NULL DEFAULT localtimestamp,
    "DailyCapacityHours" numeric(4, 2) NULL,
    "IsAssignable"       boolean NOT NULL DEFAULT true
);

-- ---------------------------------------------------------------------
-- Roles
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Roles" (
    "RoleId"      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RoleName"    varchar(50)  NOT NULL,
    "RoleCode"    varchar(50)  NOT NULL,
    "Description" varchar(255) NULL,
    "IsActive"    boolean NOT NULL DEFAULT true,
    "CreatedAt"   timestamp(6) NOT NULL DEFAULT localtimestamp,
    CONSTRAINT "UQ_Roles_RoleCode" UNIQUE ("RoleCode")
);

-- ---------------------------------------------------------------------
-- Departments
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Departments" (
    "DepartmentId"   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DepartmentName" varchar(100) NOT NULL,
    CONSTRAINT "UQ_Departments_DepartmentName" UNIQUE ("DepartmentName")
);

-- ---------------------------------------------------------------------
-- Users
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Users" (
    "UserId"       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeId"   integer NOT NULL,
    "Username"     varchar(50)  NOT NULL,
    "Email"        varchar(100) NOT NULL,
    "PasswordHash" varchar(255) NOT NULL,
    "IsActive"     boolean NOT NULL DEFAULT true,
    "LastLoginAt"  timestamp(6) NULL,
    "CreatedAt"    timestamp(6) NOT NULL DEFAULT localtimestamp,
    "PasswordSalt" varchar(500) NOT NULL DEFAULT '',
    "Phone"        varchar(50)  NULL,
    "Notes"        varchar(500) NULL,
    CONSTRAINT "UQ_Users_Username" UNIQUE ("Username"),
    CONSTRAINT "UQ_Users_Email" UNIQUE ("Email"),
    CONSTRAINT "FK_Users_Employees" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("EmployeeId")
);

CREATE INDEX IF NOT EXISTS "IX_Users_EmployeeId" ON "Users" ("EmployeeId");

-- ---------------------------------------------------------------------
-- UserRoles
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "UserRoles" (
    "UserRoleId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"     integer NOT NULL,
    "RoleId"     integer NOT NULL,
    "AssignedAt" timestamp(6) NOT NULL DEFAULT localtimestamp,
    "IsActive"   boolean NOT NULL DEFAULT true,
    "RemovedAt"  timestamp(6) NULL,
    CONSTRAINT "UQ_UserRoles_UserId_RoleId" UNIQUE ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Users" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId"),
    CONSTRAINT "FK_UserRoles_Roles" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("RoleId")
);

CREATE INDEX IF NOT EXISTS "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");
CREATE INDEX IF NOT EXISTS "IX_UserRoles_UserId" ON "UserRoles" ("UserId");

-- ---------------------------------------------------------------------
-- UserDepartments
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "UserDepartments" (
    "UserDepartmentId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"           integer NOT NULL,
    "DepartmentId"     integer NOT NULL,
    "AssignedAt"       timestamp(6) NOT NULL DEFAULT localtimestamp,
    "IsActive"         boolean NOT NULL DEFAULT true,
    "RemovedAt"        timestamp(6) NULL,
    CONSTRAINT "UQ_UserDepartments_UserId_DepartmentId" UNIQUE ("UserId", "DepartmentId"),
    CONSTRAINT "FK_UserDepartments_Users" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId"),
    CONSTRAINT "FK_UserDepartments_Departments" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("DepartmentId")
);

-- ---------------------------------------------------------------------
-- CompanySettings (single-row table)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "CompanySettings" (
    "CompanySettingsId"  smallint NOT NULL PRIMARY KEY,
    "CompanyName"        varchar(200) NOT NULL,
    "LegalName"          varchar(200) NULL,
    "RegistrationNumber" varchar(50)  NULL,
    "Email"              varchar(254) NULL,
    "Phone"              varchar(50)  NULL,
    "Address"            varchar(500) NULL,
    "Website"            varchar(250) NULL,
    "UpdatedAt"          timestamp(0) NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedByUserId"    integer NULL,
    CONSTRAINT "CK_CompanySettings_SingleRow" CHECK ("CompanySettingsId" = 1)
);
