-- =====================================================================
-- ManageR2 PostgreSQL schema - Customers / Sites / Contacts (Wave 2)
-- Translated from database/schema/tables.sql (SQL Server baseline).
-- Depends on 01_core_identity.sql (Users FK targets).
-- =====================================================================

-- ---------------------------------------------------------------------
-- Customers
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Customers" (
    "CustomerId"      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CustomerName"    varchar(200) NOT NULL,
    "CustomerType"    varchar(50)  NOT NULL,
    "Phone"           varchar(20)  NULL,
    "Email"           varchar(100) NULL,
    "IsActive"        boolean NOT NULL DEFAULT true,
    "CreatedAt"       timestamp(6) NOT NULL DEFAULT localtimestamp,
    "PrimaryPhone"    varchar(50)  NULL,
    "PrimaryEmail"    varchar(255) NULL,
    "City"            varchar(100) NULL,
    "Region"          varchar(100) NULL,
    "Address"         varchar(255) NULL,
    "Status"          varchar(50)  NULL,
    "Notes"           varchar(1000) NULL,
    "CreatedByUserId" integer NOT NULL,
    "UpdatedAt"       timestamp(0) NULL,
    "UpdatedByUserId" integer NULL,
    CONSTRAINT "FK_Customers_CreatedByUser" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("UserId"),
    CONSTRAINT "FK_Customers_UpdatedByUser" FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users" ("UserId")
);

CREATE INDEX IF NOT EXISTS "IX_Customers_CustomerName" ON "Customers" ("CustomerName");
CREATE INDEX IF NOT EXISTS "IX_Customers_CustomerType_IsActive" ON "Customers" ("CustomerType", "IsActive");

-- ---------------------------------------------------------------------
-- Sites
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Sites" (
    "SiteId"      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CustomerId"  integer NOT NULL,
    "SiteName"    varchar(100) NOT NULL,
    "AddressLine" varchar(200) NULL,
    "City"        varchar(50)  NULL,
    "IsPrimary"   boolean NOT NULL DEFAULT false,
    "Notes"       varchar(500) NULL,
    "CreatedAt"   timestamp(6) NOT NULL DEFAULT localtimestamp,
    "IsActive"    boolean NOT NULL DEFAULT true,
    "UpdatedAt"   timestamp(6) NULL,
    "DeletedAt"   timestamp(6) NULL,
    CONSTRAINT "FK_Sites_Customers" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("CustomerId")
);

CREATE INDEX IF NOT EXISTS "IX_Sites_CustomerId" ON "Sites" ("CustomerId");

-- ---------------------------------------------------------------------
-- Contacts
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Contacts" (
    "ContactId"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FullName"         varchar(200) NOT NULL,
    "JobTitle"         varchar(150) NULL,
    "ContactCategory"  varchar(50)  NOT NULL,
    "CustomerId"       integer NULL,
    "CompanyName"      varchar(200) NULL,
    "Phone"            varchar(50)  NULL,
    "SecondaryPhone"   varchar(50)  NULL,
    "Email"            varchar(255) NULL,
    "PreferredChannel" varchar(50)  NULL,
    "City"             varchar(100) NULL,
    "Address"          varchar(255) NULL,
    "Status"           varchar(50)  NULL,
    "Notes"            varchar(1000) NULL,
    "IsActive"         boolean NOT NULL DEFAULT true,
    "CreatedAt"        timestamp(0) NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedByUserId"  integer NOT NULL,
    "UpdatedAt"        timestamp(0) NULL,
    "UpdatedByUserId"  integer NULL,
    CONSTRAINT "FK_Contacts_Customers" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("CustomerId"),
    CONSTRAINT "FK_Contacts_CreatedByUser" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("UserId"),
    CONSTRAINT "FK_Contacts_UpdatedByUser" FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users" ("UserId"),
    CONSTRAINT "CK_Contacts_ContactCategory" CHECK (
        "ContactCategory" IN ('Other','Contractor','Architect','Consultant','BusinessPartner','Supplier','CustomerRepresentative','CustomerPrimary')
    ),
    CONSTRAINT "CK_Contacts_CustomerRequiredByCategory" CHECK (
        ("ContactCategory" IN ('CustomerRepresentative','CustomerPrimary') AND "CustomerId" IS NOT NULL)
        OR "ContactCategory" NOT IN ('CustomerRepresentative','CustomerPrimary')
    ),
    CONSTRAINT "CK_Contacts_PhoneOrEmailRequired" CHECK (
        NULLIF(btrim(COALESCE("Phone", '')), '') IS NOT NULL
        OR NULLIF(btrim(COALESCE("Email", '')), '') IS NOT NULL
    )
);

CREATE INDEX IF NOT EXISTS "IX_Contacts_Category_IsActive" ON "Contacts" ("ContactCategory", "IsActive");
CREATE INDEX IF NOT EXISTS "IX_Contacts_CustomerId" ON "Contacts" ("CustomerId");
CREATE INDEX IF NOT EXISTS "IX_Contacts_FullName" ON "Contacts" ("FullName");
