-- =====================================================================
-- ManageR2 PostgreSQL schema - WorkItems / Projects / Quotes / Assignments (Wave 3)
-- Translated from database/schema/tables.sql (SQL Server baseline).
-- Depends on 01_core_identity.sql and 02_customers_sites_contacts.sql.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Contractors
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Contractors" (
    "ContractorId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FullName"     varchar(100) NOT NULL,
    "CompanyName"  varchar(100) NULL,
    "Phone"        varchar(20)  NULL,
    "Email"        varchar(100) NULL,
    "IsActive"     boolean NOT NULL DEFAULT true,
    "CreatedAt"    timestamp(6) NOT NULL DEFAULT localtimestamp
);

-- ---------------------------------------------------------------------
-- WorkItems (central table; self-referencing ParentWorkItemId)
-- ---------------------------------------------------------------------
-- CustomerId is nullable (migration 2026-06-19_workplan_reports_overhaul made it NULL).
-- TaskCategory / MilestoneId / IsArchived / ArchivedAt were added by the same migration; the
-- CHECK constraints enforce the schedulable-category invariants. The FK_WorkItems_Milestone
-- constraint is added after ProjectMilestones exists (circular dependency).
CREATE TABLE IF NOT EXISTS "WorkItems" (
    "WorkItemId"           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title"                varchar(150) NOT NULL,
    "WorkType"             varchar(50)  NOT NULL,
    "Status"               varchar(50)  NOT NULL,
    "BillingType"          varchar(50)  NULL,
    "Description"          varchar(1000) NULL,
    "CustomerId"           integer NULL,
    "SiteId"               integer NULL,
    "CreatedAt"            timestamp(6) NOT NULL DEFAULT localtimestamp,
    "ClosedAt"             timestamp(6) NULL,
    "ParentWorkItemId"     integer NULL,
    "DealCloseDate"        timestamp(6) NULL,
    "FinanceProjectNumber" varchar(100) NULL,
    "InvoiceNumber"        varchar(100) NULL,
    "EstimatedHours"       numeric(5, 2) NULL,
    "Priority"             varchar(20)  NULL,
    "PlannedStart"         timestamp(6) NULL,
    "PlannedEnd"           timestamp(6) NULL,
    "RequiredRole"         varchar(100) NULL,
    "IsLocked"             boolean NOT NULL DEFAULT false,
    "ActualStart"          timestamp(3) NULL,
    "ActualEnd"            timestamp(3) NULL,
    "ActualHours"          numeric(10, 2) NULL,
    "TaskCategory"         varchar(20)  NULL,
    "MilestoneId"          integer NULL,
    "IsArchived"           boolean NOT NULL DEFAULT false,
    "ArchivedAt"           timestamp(6) NULL,
    CONSTRAINT "FK_WorkItems_Customers" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("CustomerId"),
    CONSTRAINT "FK_WorkItems_Sites" FOREIGN KEY ("SiteId") REFERENCES "Sites" ("SiteId"),
    CONSTRAINT "FK_WorkItems_ParentWorkItem" FOREIGN KEY ("ParentWorkItemId") REFERENCES "WorkItems" ("WorkItemId"),
    CONSTRAINT "CK_WorkItems_TypeCategory" CHECK (
        CASE
            WHEN "IsArchived" = true THEN 1
            WHEN "WorkType" = 'Project' AND "TaskCategory" IS NULL AND "ParentWorkItemId" IS NULL AND "MilestoneId" IS NULL THEN 1
            WHEN "WorkType" = 'Task' AND "TaskCategory" = 'Regular' AND "ParentWorkItemId" IS NULL AND "MilestoneId" IS NULL THEN 1
            WHEN "WorkType" = 'Task' AND "TaskCategory" = 'Project' AND "ParentWorkItemId" IS NOT NULL THEN 1
            WHEN "WorkType" = 'ServiceCall' AND "TaskCategory" = 'ServiceCall' AND "ParentWorkItemId" IS NULL AND "MilestoneId" IS NULL THEN 1
            ELSE 0
        END = 1
    ),
    CONSTRAINT "CK_WorkItems_RegularNoProject" CHECK (
        CASE
            WHEN "IsArchived" = true THEN 1
            WHEN "WorkType" <> 'Task' THEN 1
            WHEN "TaskCategory" IS NULL THEN 0
            WHEN "TaskCategory" <> 'Regular' THEN 1
            WHEN "ParentWorkItemId" IS NULL AND "MilestoneId" IS NULL THEN 1
            ELSE 0
        END = 1
    ),
    CONSTRAINT "CK_WorkItems_ArchiveMetadata" CHECK ("IsArchived" = false OR "ArchivedAt" IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS "IX_WorkItems_CustomerId" ON "WorkItems" ("CustomerId");
CREATE INDEX IF NOT EXISTS "IX_WorkItems_SiteId" ON "WorkItems" ("SiteId");
CREATE INDEX IF NOT EXISTS "IX_WorkItems_TaskCategory" ON "WorkItems" ("TaskCategory");
CREATE INDEX IF NOT EXISTS "IX_WorkItems_MilestoneId" ON "WorkItems" ("MilestoneId") WHERE "MilestoneId" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "IX_WorkItems_IsArchived" ON "WorkItems" ("IsArchived", "WorkType", "TaskCategory");

-- ---------------------------------------------------------------------
-- ProjectMilestones (dedicated non-schedulable milestones; migration-delivered)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "ProjectMilestones" (
    "ProjectMilestoneId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProjectId"          integer NOT NULL,
    "Title"              varchar(200) NOT NULL,
    "Description"        varchar(1000) NULL,
    "SortOrder"          integer NOT NULL DEFAULT 0,
    "Status"             varchar(50) NOT NULL DEFAULT 'Planned',
    "PlannedStart"       timestamp(6) NULL,
    "PlannedEnd"         timestamp(6) NULL,
    "ActualStart"        timestamp(6) NULL,
    "ActualEnd"          timestamp(6) NULL,
    "ProgressPercent"    numeric(5, 2) NOT NULL DEFAULT 0,
    "IsActive"           boolean NOT NULL DEFAULT true,
    "CreatedAt"          timestamp(6) NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt"          timestamp(6) NULL,
    "LegacyWorkItemId"   integer NULL,
    CONSTRAINT "FK_ProjectMilestones_Project" FOREIGN KEY ("ProjectId") REFERENCES "WorkItems" ("WorkItemId"),
    CONSTRAINT "FK_ProjectMilestones_LegacyWorkItem" FOREIGN KEY ("LegacyWorkItemId") REFERENCES "WorkItems" ("WorkItemId"),
    CONSTRAINT "CK_ProjectMilestones_Title" CHECK (length(btrim("Title")) > 0),
    CONSTRAINT "CK_ProjectMilestones_Progress" CHECK ("ProgressPercent" BETWEEN 0 AND 100),
    CONSTRAINT "CK_ProjectMilestones_SortOrder" CHECK ("SortOrder" >= 0),
    CONSTRAINT "CK_ProjectMilestones_PlannedRange" CHECK (
        ("PlannedStart" IS NULL AND "PlannedEnd" IS NULL) OR
        ("PlannedStart" IS NOT NULL AND "PlannedEnd" IS NOT NULL AND "PlannedEnd" >= "PlannedStart")
    ),
    CONSTRAINT "CK_ProjectMilestones_ActualRange" CHECK (
        ("ActualStart" IS NULL AND "ActualEnd" IS NULL) OR
        ("ActualStart" IS NOT NULL AND "ActualEnd" IS NOT NULL AND "ActualEnd" > "ActualStart")
    )
);

CREATE INDEX IF NOT EXISTS "IX_ProjectMilestones_Project_Sort"
    ON "ProjectMilestones" ("ProjectId", "IsActive", "SortOrder", "ProjectMilestoneId");
CREATE UNIQUE INDEX IF NOT EXISTS "UX_ProjectMilestones_LegacyWorkItemId"
    ON "ProjectMilestones" ("LegacyWorkItemId") WHERE "LegacyWorkItemId" IS NOT NULL;

-- Circular FK: WorkItems.MilestoneId -> ProjectMilestones (added after both tables exist).
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_WorkItems_Milestone') THEN
        ALTER TABLE "WorkItems"
            ADD CONSTRAINT "FK_WorkItems_Milestone"
            FOREIGN KEY ("MilestoneId") REFERENCES "ProjectMilestones" ("ProjectMilestoneId");
    END IF;
END $$;

-- ---------------------------------------------------------------------
-- ProjectEquipmentItems
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "ProjectEquipmentItems" (
    "ProjectEquipmentItemId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProjectId"              integer NOT NULL,
    "EquipmentName"          varchar(200) NOT NULL,
    "Status"                 varchar(50)  NOT NULL,
    "Location"               varchar(200) NULL,
    "SortOrder"              integer NOT NULL,
    "CreatedAt"              timestamp(6) NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt"              timestamp(6) NULL,
    CONSTRAINT "FK_ProjectEquipmentItems_WorkItems" FOREIGN KEY ("ProjectId") REFERENCES "WorkItems" ("WorkItemId"),
    CONSTRAINT "CK_ProjectEquipmentItems_EquipmentName_NotBlank" CHECK (length(btrim("EquipmentName")) > 0),
    CONSTRAINT "CK_ProjectEquipmentItems_Status_NotBlank" CHECK (length(btrim("Status")) > 0)
);

CREATE INDEX IF NOT EXISTS "IX_ProjectEquipmentItems_ProjectId_SortOrder"
    ON "ProjectEquipmentItems" ("ProjectId", "SortOrder", "ProjectEquipmentItemId");

-- ---------------------------------------------------------------------
-- ProjectBoqItems
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "ProjectBoqItems" (
    "ProjectBoqItemId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProjectId"        integer NOT NULL,
    "SystemName"       varchar(200) NULL,
    "ItemDescription"  varchar(500) NOT NULL,
    "Quantity"         numeric(18, 2) NOT NULL,
    "Unit"             varchar(50)  NOT NULL,
    "SortOrder"        integer NOT NULL,
    "IsActive"         boolean NOT NULL DEFAULT true,
    "CreatedAt"        timestamp(6) NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt"        timestamp(6) NULL,
    "DeletedAt"        timestamp(6) NULL,
    CONSTRAINT "FK_ProjectBoqItems_WorkItems" FOREIGN KEY ("ProjectId") REFERENCES "WorkItems" ("WorkItemId"),
    CONSTRAINT "CK_ProjectBoqItems_ItemDescription_NotBlank" CHECK (length(btrim("ItemDescription")) > 0),
    CONSTRAINT "CK_ProjectBoqItems_Quantity_Positive" CHECK ("Quantity" > 0),
    CONSTRAINT "CK_ProjectBoqItems_Unit_NotBlank" CHECK (length(btrim("Unit")) > 0)
);

CREATE INDEX IF NOT EXISTS "IX_ProjectBoqItems_ProjectId_SortOrder"
    ON "ProjectBoqItems" ("ProjectId", "SortOrder", "ProjectBoqItemId")
    WHERE ("IsActive" = true);

-- ---------------------------------------------------------------------
-- ProjectDrawings
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "ProjectDrawings" (
    "ProjectDrawingId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProjectId"        integer NOT NULL,
    "Name"             varchar(200) NOT NULL,
    "Type"             varchar(20)  NOT NULL,
    "DrawingDate"      date NOT NULL,
    "Note"             varchar(500) NULL,
    "SortOrder"        integer NOT NULL,
    "IsActive"         boolean NOT NULL DEFAULT true,
    "CreatedAt"        timestamp(6) NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt"        timestamp(6) NULL,
    "DeletedAt"        timestamp(6) NULL,
    CONSTRAINT "FK_ProjectDrawings_WorkItems" FOREIGN KEY ("ProjectId") REFERENCES "WorkItems" ("WorkItemId"),
    CONSTRAINT "CK_ProjectDrawings_Name_NotBlank" CHECK (length(btrim("Name")) > 0),
    CONSTRAINT "CK_ProjectDrawings_Type" CHECK ("Type" IN ('DWG', 'PDF'))
);

CREATE INDEX IF NOT EXISTS "IX_ProjectDrawings_ProjectId_SortOrder"
    ON "ProjectDrawings" ("ProjectId", "SortOrder", "ProjectDrawingId")
    WHERE ("IsActive" = true);

-- ---------------------------------------------------------------------
-- Quotes
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Quotes" (
    "QuoteId"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "QuoteNumber"     varchar(50)  NOT NULL,
    "CustomerId"      integer NOT NULL,
    "ProjectId"       integer NULL,
    "QuoteDate"       date NOT NULL,
    "ValidUntil"      date NULL,
    "Status"          varchar(50)  NOT NULL DEFAULT 'Draft',
    "Notes"           varchar(1000) NULL,
    "VatRate"         numeric(5, 2) NOT NULL DEFAULT 17.00,
    "Subtotal"        numeric(18, 2) NOT NULL DEFAULT 0,
    "VatAmount"       numeric(18, 2) NOT NULL DEFAULT 0,
    "Total"           numeric(18, 2) NOT NULL DEFAULT 0,
    "IsActive"        boolean NOT NULL DEFAULT true,
    "CreatedAt"       timestamp(6) NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedByUserId" integer NULL,
    "UpdatedAt"       timestamp(6) NULL,
    "UpdatedByUserId" integer NULL,
    "DeletedAt"       timestamp(6) NULL,
    CONSTRAINT "FK_Quotes_Customers" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("CustomerId"),
    CONSTRAINT "FK_Quotes_WorkItems" FOREIGN KEY ("ProjectId") REFERENCES "WorkItems" ("WorkItemId"),
    CONSTRAINT "FK_Quotes_CreatedByUser" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("UserId"),
    CONSTRAINT "FK_Quotes_UpdatedByUser" FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users" ("UserId"),
    CONSTRAINT "CK_Quotes_QuoteNumber_NotBlank" CHECK (length(btrim("QuoteNumber")) > 0),
    CONSTRAINT "CK_Quotes_Status_Allowed" CHECK ("Status" IN ('Draft', 'Sent', 'Tracking', 'Approved', 'Rejected')),
    CONSTRAINT "CK_Quotes_VatRate_NonNegative" CHECK ("VatRate" >= 0)
);

-- ---------------------------------------------------------------------
-- QuoteLineItems
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "QuoteLineItems" (
    "QuoteLineItemId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "QuoteId"         integer NOT NULL,
    "Description"     varchar(500) NOT NULL,
    "Quantity"        numeric(18, 2) NOT NULL,
    "Unit"            varchar(50)  NOT NULL,
    "UnitPrice"       numeric(18, 2) NOT NULL,
    "LineTotal"       numeric(18, 2) NOT NULL DEFAULT 0,
    "SortOrder"       integer NOT NULL DEFAULT 1,
    "CreatedAt"       timestamp(6) NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt"       timestamp(6) NULL,
    CONSTRAINT "FK_QuoteLineItems_Quotes" FOREIGN KEY ("QuoteId") REFERENCES "Quotes" ("QuoteId"),
    CONSTRAINT "CK_QuoteLineItems_Description_NotBlank" CHECK (length(btrim("Description")) > 0),
    CONSTRAINT "CK_QuoteLineItems_Unit_NotBlank" CHECK (length(btrim("Unit")) > 0),
    CONSTRAINT "CK_QuoteLineItems_Quantity_NonNegative" CHECK ("Quantity" >= 0),
    CONSTRAINT "CK_QuoteLineItems_UnitPrice_NonNegative" CHECK ("UnitPrice" >= 0)
);

-- ---------------------------------------------------------------------
-- WorkEmployeeAssignments
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "WorkEmployeeAssignments" (
    "WorkEmployeeAssignmentId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "WorkItemId"               integer NOT NULL,
    "EmployeeId"               integer NOT NULL,
    "AssignmentRole"           varchar(100) NOT NULL,
    "AssignedAt"               timestamp(6) NOT NULL DEFAULT localtimestamp,
    "AssignedHours"            numeric(5, 2) NULL,
    "IsManualAssignment"       boolean NOT NULL DEFAULT false,
    CONSTRAINT "FK_WorkEmployeeAssignments_WorkItems" FOREIGN KEY ("WorkItemId") REFERENCES "WorkItems" ("WorkItemId"),
    CONSTRAINT "FK_WorkEmployeeAssignments_Employees" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("EmployeeId")
);

CREATE INDEX IF NOT EXISTS "IX_WorkEmployeeAssignments_EmployeeId" ON "WorkEmployeeAssignments" ("EmployeeId");
CREATE INDEX IF NOT EXISTS "IX_WorkEmployeeAssignments_WorkItemId" ON "WorkEmployeeAssignments" ("WorkItemId");

-- ---------------------------------------------------------------------
-- WorkContractorAssignments
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "WorkContractorAssignments" (
    "WorkContractorAssignmentId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "WorkItemId"                 integer NOT NULL,
    "ContractorId"               integer NOT NULL,
    "AssignmentRole"             varchar(100) NOT NULL,
    "AssignedAt"                 timestamp(6) NOT NULL DEFAULT localtimestamp,
    CONSTRAINT "FK_WorkContractorAssignments_WorkItems" FOREIGN KEY ("WorkItemId") REFERENCES "WorkItems" ("WorkItemId"),
    CONSTRAINT "FK_WorkContractorAssignments_Contractors" FOREIGN KEY ("ContractorId") REFERENCES "Contractors" ("ContractorId")
);

CREATE INDEX IF NOT EXISTS "IX_WorkContractorAssignments_ContractorId" ON "WorkContractorAssignments" ("ContractorId");
CREATE INDEX IF NOT EXISTS "IX_WorkContractorAssignments_WorkItemId" ON "WorkContractorAssignments" ("WorkItemId");
