-- =====================================================================
-- ManageR2 PostgreSQL schema - Inventory / WorkReports (Wave 4)
-- Translated from database/schema/tables.sql (SQL Server baseline).
-- Depends on 01_core_identity.sql (Employees) and 03_workitems_projects_quotes.sql (WorkItems).
-- NOTE: The transactional inventory finalize/reverse logic (currently in
--   sp_WorkReports_Finalize / sp_InventoryStockMovements_ApplyForReport) is reimplemented as a
--   transactional C# service under the service-refactor strategy, NOT as a plpgsql port.
-- =====================================================================

-- ---------------------------------------------------------------------
-- InventoryItems
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "InventoryItems" (
    "InventoryItemId"     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SkuCode"             varchar(50)  NOT NULL,
    "ItemName"            varchar(200) NOT NULL,
    "Category"            varchar(100) NULL,
    "QuantityOnHand"      numeric(18, 3) NOT NULL DEFAULT 0,
    "Unit"                varchar(20)  NOT NULL,
    "MinimumQuantity"     numeric(18, 3) NULL,
    "LocationName"        varchar(200) NULL,
    "Notes"               varchar(500) NULL,
    "IsActive"            boolean NOT NULL DEFAULT true,
    "CreatedAt"           timestamp(6) NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt"           timestamp(6) NULL,
    "DeletedAt"           timestamp(6) NULL,
    "ImagePath"           varchar(260) NULL,
    "ImageContentType"    varchar(100) NULL,
    "ImageFileSizeBytes"  bigint NULL,
    CONSTRAINT "CK_InventoryItems_SkuCode_NotBlank" CHECK (length(btrim("SkuCode")) > 0),
    CONSTRAINT "CK_InventoryItems_ItemName_NotBlank" CHECK (length(btrim("ItemName")) > 0),
    CONSTRAINT "CK_InventoryItems_QuantityOnHand_NonNegative" CHECK ("QuantityOnHand" >= 0),
    CONSTRAINT "CK_InventoryItems_Unit_NotBlank" CHECK (length(btrim("Unit")) > 0),
    CONSTRAINT "CK_InventoryItems_MinimumQuantity_NonNegative" CHECK ("MinimumQuantity" IS NULL OR "MinimumQuantity" >= 0),
    CONSTRAINT "CK_InventoryItems_ImageFileSizeBytes_NonNegative" CHECK ("ImageFileSizeBytes" IS NULL OR "ImageFileSizeBytes" >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_InventoryItems_SkuCode_Active"
    ON "InventoryItems" ("SkuCode")
    WHERE ("IsActive" = true);
CREATE INDEX IF NOT EXISTS "IX_InventoryItems_IsActive_ItemName"
    ON "InventoryItems" ("IsActive", "ItemName", "InventoryItemId");
CREATE INDEX IF NOT EXISTS "IX_InventoryItems_Category_IsActive"
    ON "InventoryItems" ("Category", "IsActive");

-- ---------------------------------------------------------------------
-- WorkReports
--   Status default preserves the Hebrew business workflow value (draft).
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "WorkReports" (
    "WorkReportId"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "WorkItemId"          integer NULL,
    "ReportType"          varchar(50)  NULL,
    "ReportDate"          timestamp(3) NULL,
    "ProjectName"         varchar(150) NULL,
    "CustomerName"        varchar(150) NULL,
    "Site"                varchar(200) NULL,
    "StartTime"           varchar(10)  NULL,
    "EndTime"             varchar(10)  NULL,
    "Summary"             varchar(1000) NULL,
    "Notes"               varchar(2000) NULL,
    "ReporterEmployeeId"  integer NULL,
    "ReporterName"        varchar(100) NULL,
    "ReporterRole"        varchar(100) NULL,
    "WorkersCount"        integer NULL DEFAULT 0,
    "FollowUpRequired"    boolean NULL DEFAULT false,
    "FollowUpReason"      varchar(1000) NULL,
    "CreatedAt"           timestamp(3) NULL DEFAULT localtimestamp,
    "Status"              varchar(50)  NOT NULL DEFAULT 'טיוטה',
    -- Independent report lifecycle (2026-06-19 overhaul). Status stays the Hebrew workflow status;
    -- LifecycleStatus separately controls Draft/Finalized/Reversed and inventory finalization.
    "LifecycleStatus"     varchar(20)  NOT NULL DEFAULT 'Draft',
    "FinalizedAt"         timestamp(6) NULL,
    "FinalizedByUserId"   integer NULL,
    "ReversedAt"          timestamp(6) NULL,
    "ReversedByUserId"    integer NULL,
    "ReversalReason"      varchar(500) NULL,
    "AmendsWorkReportId"  integer NULL,
    "UpdatedAt"           timestamp(6) NULL,
    "UpdatedByUserId"     integer NULL,
    CONSTRAINT "FK_WorkReports_WorkItems" FOREIGN KEY ("WorkItemId") REFERENCES "WorkItems" ("WorkItemId"),
    CONSTRAINT "FK_WorkReports_Employees" FOREIGN KEY ("ReporterEmployeeId") REFERENCES "Employees" ("EmployeeId"),
    CONSTRAINT "FK_WorkReports_FinalizedByUser" FOREIGN KEY ("FinalizedByUserId") REFERENCES "Users" ("UserId"),
    CONSTRAINT "FK_WorkReports_ReversedByUser" FOREIGN KEY ("ReversedByUserId") REFERENCES "Users" ("UserId"),
    CONSTRAINT "FK_WorkReports_UpdatedByUser" FOREIGN KEY ("UpdatedByUserId") REFERENCES "Users" ("UserId"),
    CONSTRAINT "FK_WorkReports_AmendsWorkReport" FOREIGN KEY ("AmendsWorkReportId") REFERENCES "WorkReports" ("WorkReportId"),
    CONSTRAINT "CK_WorkReports_LifecycleStatus" CHECK ("LifecycleStatus" IN ('Draft', 'Finalized', 'Reversed')),
    CONSTRAINT "CK_WorkReports_LifecycleMetadata" CHECK (
        ("LifecycleStatus" IN ('Draft', 'Finalized') AND "ReversedAt" IS NULL AND "ReversedByUserId" IS NULL AND "ReversalReason" IS NULL)
        OR ("LifecycleStatus" = 'Reversed' AND "ReversedAt" IS NOT NULL AND length(btrim("ReversalReason")) > 0)
    ),
    CONSTRAINT "CK_WorkReports_NotSelfAmend" CHECK ("AmendsWorkReportId" IS NULL OR "AmendsWorkReportId" <> "WorkReportId")
);

CREATE INDEX IF NOT EXISTS "IX_WorkReports_LifecycleStatus"
    ON "WorkReports" ("LifecycleStatus", "WorkReportId");
CREATE INDEX IF NOT EXISTS "IX_WorkReports_AmendsWorkReportId"
    ON "WorkReports" ("AmendsWorkReportId")
    WHERE ("AmendsWorkReportId" IS NOT NULL);
CREATE INDEX IF NOT EXISTS "IX_WorkReports_WorkItemId"
    ON "WorkReports" ("WorkItemId")
    WHERE ("WorkItemId" IS NOT NULL);

-- ---------------------------------------------------------------------
-- WorkReportEmployeeAssignments
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "WorkReportEmployeeAssignments" (
    "WorkReportEmployeeAssignmentId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "WorkReportId"                   integer NULL,
    "EmployeeId"                     integer NULL,
    "EmployeeName"                   varchar(100) NULL,
    "AssignmentRole"                 varchar(100) NULL,
    "AssignedAt"                     timestamp(3) NULL DEFAULT localtimestamp,
    CONSTRAINT "FK_WorkReportEmployeeAssignments_WorkReports" FOREIGN KEY ("WorkReportId") REFERENCES "WorkReports" ("WorkReportId"),
    CONSTRAINT "FK_WorkReportEmployeeAssignments_Employees" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("EmployeeId")
);

-- ---------------------------------------------------------------------
-- WorkReportSystems
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "WorkReportSystems" (
    "WorkReportSystemId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "WorkReportId"       integer NULL,
    "SystemName"         varchar(100) NULL,
    "CreatedAt"          timestamp(3) NULL DEFAULT localtimestamp,
    CONSTRAINT "FK_WorkReportSystems_WorkReports" FOREIGN KEY ("WorkReportId") REFERENCES "WorkReports" ("WorkReportId")
);

-- ---------------------------------------------------------------------
-- WorkReportInventoryItems (2026-06-19 overhaul)
--   Immutable per-report inventory lines. UNIQUE(report, item, usage) mirrors the SQL Server
--   MERGE upsert key in sp_WorkReportInventory_Add.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "WorkReportInventoryItems" (
    "WorkReportInventoryItemId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "WorkReportId"              integer NOT NULL,
    "InventoryItemId"          integer NOT NULL,
    "Quantity"                 numeric(18, 3) NOT NULL,
    "UsageType"                varchar(20)  NOT NULL,
    "SkuSnapshot"              varchar(50)  NOT NULL,
    "ItemNameSnapshot"         varchar(200) NOT NULL,
    "CreatedAt"                timestamp(6) NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedByUserId"          integer NULL,
    CONSTRAINT "FK_WorkReportInventoryItems_Report" FOREIGN KEY ("WorkReportId") REFERENCES "WorkReports" ("WorkReportId"),
    CONSTRAINT "FK_WorkReportInventoryItems_Item" FOREIGN KEY ("InventoryItemId") REFERENCES "InventoryItems" ("InventoryItemId"),
    CONSTRAINT "FK_WorkReportInventoryItems_User" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("UserId"),
    CONSTRAINT "CK_WorkReportInventoryItems_Quantity" CHECK ("Quantity" > 0),
    CONSTRAINT "CK_WorkReportInventoryItems_UsageType" CHECK ("UsageType" IN ('Sold', 'Installed', 'Used')),
    CONSTRAINT "UQ_WorkReportInventoryItems_Report_Item_Usage" UNIQUE ("WorkReportId", "InventoryItemId", "UsageType")
);

CREATE INDEX IF NOT EXISTS "IX_WorkReportInventoryItems_Item"
    ON "WorkReportInventoryItems" ("InventoryItemId", "WorkReportId");

-- ---------------------------------------------------------------------
-- WorkReportAttachments (2026-06-19 overhaul)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "WorkReportAttachments" (
    "WorkReportAttachmentId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "WorkReportId"           integer NOT NULL,
    "MediaType"              varchar(20)  NOT NULL,
    "OriginalFileName"       varchar(255) NOT NULL,
    "StoredFileName"         varchar(255) NOT NULL,
    "FilePath"               varchar(500) NOT NULL,
    "ContentType"            varchar(100) NOT NULL,
    "FileSizeBytes"          bigint NOT NULL,
    "UploadedAt"             timestamp(6) NOT NULL DEFAULT (now() at time zone 'utc'),
    "UploadedByUserId"       integer NULL,
    CONSTRAINT "FK_WorkReportAttachments_Report" FOREIGN KEY ("WorkReportId") REFERENCES "WorkReports" ("WorkReportId"),
    CONSTRAINT "FK_WorkReportAttachments_User" FOREIGN KEY ("UploadedByUserId") REFERENCES "Users" ("UserId"),
    CONSTRAINT "CK_WorkReportAttachments_MediaType" CHECK ("MediaType" IN ('Image', 'Video')),
    CONSTRAINT "CK_WorkReportAttachments_FileSize" CHECK ("FileSizeBytes" > 0),
    CONSTRAINT "UQ_WorkReportAttachments_StoredFileName" UNIQUE ("StoredFileName")
);

CREATE INDEX IF NOT EXISTS "IX_WorkReportAttachments_Report"
    ON "WorkReportAttachments" ("WorkReportId", "UploadedAt", "WorkReportAttachmentId");

-- ---------------------------------------------------------------------
-- InventoryStockMovements (2026-06-19 overhaul)
--   Immutable ledger written by the C# transactional inventory finalize/reverse orchestration
--   (service-refactor reimplementation of sp_InventoryStockMovements_ApplyForReport). The filtered
--   UNIQUE(line, movement type) index enforces idempotency: at most one usage and one reversal per line.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "InventoryStockMovements" (
    "InventoryStockMovementId"   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "InventoryItemId"            integer NOT NULL,
    "WorkReportInventoryItemId"  integer NULL,
    "QuantityDelta"              numeric(18, 3) NOT NULL,
    "MovementType"               varchar(30)  NOT NULL,
    "SourceType"                 varchar(50)  NULL,
    "SourceId"                   integer NULL,
    "UsageType"                  varchar(20)  NULL,
    "CreatedAt"                  timestamp(6) NOT NULL DEFAULT (now() at time zone 'utc'),
    "CreatedByUserId"            integer NULL,
    CONSTRAINT "FK_InventoryStockMovements_Item" FOREIGN KEY ("InventoryItemId") REFERENCES "InventoryItems" ("InventoryItemId"),
    CONSTRAINT "FK_InventoryStockMovements_ReportLine" FOREIGN KEY ("WorkReportInventoryItemId") REFERENCES "WorkReportInventoryItems" ("WorkReportInventoryItemId"),
    CONSTRAINT "FK_InventoryStockMovements_User" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("UserId"),
    CONSTRAINT "CK_InventoryStockMovements_NonZero" CHECK ("QuantityDelta" <> 0),
    CONSTRAINT "CK_InventoryStockMovements_Type" CHECK ("MovementType" IN ('ReportUsage', 'ReportReversal')),
    CONSTRAINT "CK_InventoryStockMovements_Sign" CHECK (
        ("MovementType" = 'ReportUsage' AND "QuantityDelta" < 0)
        OR ("MovementType" = 'ReportReversal' AND "QuantityDelta" > 0)
    ),
    CONSTRAINT "CK_InventoryStockMovements_UsageType" CHECK ("UsageType" IS NULL OR "UsageType" IN ('Sold', 'Installed', 'Used')),
    CONSTRAINT "CK_InventoryStockMovements_SourcePair" CHECK (
        ("SourceType" IS NULL AND "SourceId" IS NULL) OR ("SourceType" IS NOT NULL AND "SourceId" IS NOT NULL)
    ),
    CONSTRAINT "CK_InventoryStockMovements_ReportSource" CHECK (
        "SourceType" IS NULL OR ("SourceType" = 'WorkReport' AND "WorkReportInventoryItemId" IS NOT NULL AND "UsageType" IS NOT NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_InventoryStockMovements_Line_Type"
    ON "InventoryStockMovements" ("WorkReportInventoryItemId", "MovementType")
    WHERE ("WorkReportInventoryItemId" IS NOT NULL);
CREATE INDEX IF NOT EXISTS "IX_InventoryStockMovements_Source"
    ON "InventoryStockMovements" ("SourceType", "SourceId", "InventoryStockMovementId");
CREATE INDEX IF NOT EXISTS "IX_InventoryStockMovements_Item"
    ON "InventoryStockMovements" ("InventoryItemId", "InventoryStockMovementId");
