-- =====================================================================
-- ManageR2 PostgreSQL schema - SmartAssignment (Rec_*) domain (Wave 5)
-- Translated from database/schema/tables.sql (SQL Server baseline).
-- Depends on 01 (Employees, Users), 02 (Sites), 03 (WorkItems).
-- JSON snapshot columns are kept as text to preserve exact content and avoid migration cast
-- failures; converting to jsonb is an optional later optimization.
-- Apply order below respects FK dependencies.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Rec_WorkZones
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Rec_WorkZones" (
    "ZoneId"      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ZoneName"    varchar(100) NOT NULL,
    "Description" varchar(255) NULL,
    "IsActive"    boolean NOT NULL DEFAULT true,
    "CreatedAt"   timestamp(0) NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "UQ_Rec_WorkZones_ZoneName" UNIQUE ("ZoneName")
);

-- ---------------------------------------------------------------------
-- Rec_Skills
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Rec_Skills" (
    "SkillId"       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SkillName"     varchar(100) NOT NULL,
    "SkillCategory" varchar(100) NULL,
    "Description"   varchar(255) NULL,
    "IsActive"      boolean NOT NULL DEFAULT true,
    "CreatedAt"     timestamp(0) NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "UQ_Rec_Skills_SkillName" UNIQUE ("SkillName")
);

-- ---------------------------------------------------------------------
-- Rec_EmployeeAvailability
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Rec_EmployeeAvailability" (
    "EmployeeAvailabilityId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeId"             integer NOT NULL,
    "AvailableFrom"          timestamp(0) NOT NULL,
    "AvailableTo"            timestamp(0) NOT NULL,
    "AvailabilityType"       varchar(20)  NOT NULL,
    "Source"                 varchar(50)  NULL,
    "Notes"                  varchar(500) NULL,
    "CreatedAt"              timestamp(0) NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "FK_Rec_EmployeeAvailability_Employees" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("EmployeeId"),
    CONSTRAINT "CK_Rec_EmployeeAvailability_TimeRange" CHECK ("AvailableFrom" < "AvailableTo"),
    CONSTRAINT "CK_Rec_EmployeeAvailability_Type" CHECK ("AvailabilityType" IN ('Training','Sick','Leave','Busy','Available'))
);

CREATE INDEX IF NOT EXISTS "IX_Rec_EmployeeAvailability_EmployeeId_TimeRange"
    ON "Rec_EmployeeAvailability" ("EmployeeId", "AvailableFrom", "AvailableTo");

-- ---------------------------------------------------------------------
-- Rec_EmployeeBaseAddress
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Rec_EmployeeBaseAddress" (
    "EmployeeBaseAddressId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeId"            integer NOT NULL,
    "InputAddress"          varchar(300) NOT NULL,
    "FormattedAddress"      varchar(300) NULL,
    "ValidationProvider"    varchar(50)  NULL,
    "ValidationStatus"      varchar(30)  NULL,
    "ValidationVerdict"     varchar(50)  NULL,
    "ValidationScore"       numeric(5, 2) NULL,
    "ExternalPlaceRef"      varchar(200) NULL,
    "Street"                varchar(200) NULL,
    "HouseNumber"           varchar(50)  NULL,
    "City"                  varchar(100) NULL,
    "Postcode"              varchar(30)  NULL,
    "StateOrRegion"         varchar(100) NULL,
    "Country"               varchar(100) NULL,
    "ZoneId"                integer NULL,
    "ValidatedAt"           timestamp(0) NULL,
    "CreatedAt"             timestamp(0) NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt"             timestamp(0) NULL,
    CONSTRAINT "UQ_Rec_EmployeeBaseAddress_EmployeeId" UNIQUE ("EmployeeId"),
    CONSTRAINT "FK_Rec_EmployeeBaseAddress_Employees" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("EmployeeId"),
    CONSTRAINT "FK_Rec_EmployeeBaseAddress_WorkZones" FOREIGN KEY ("ZoneId") REFERENCES "Rec_WorkZones" ("ZoneId"),
    CONSTRAINT "CK_Rec_EmployeeBaseAddress_ValidationScore" CHECK ("ValidationScore" IS NULL OR ("ValidationScore" >= 0 AND "ValidationScore" <= 100))
);

-- ---------------------------------------------------------------------
-- Rec_EmployeeCapacity
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Rec_EmployeeCapacity" (
    "EmployeeCapacityId"  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeId"          integer NOT NULL,
    "WeeklyCapacityHours" numeric(10, 2) NOT NULL,
    "EffectiveFrom"       date NOT NULL,
    "EffectiveTo"         date NULL,
    "Notes"               varchar(500) NULL,
    "CreatedAt"           timestamp(0) NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "FK_Rec_EmployeeCapacity_Employees" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("EmployeeId"),
    CONSTRAINT "CK_Rec_EmployeeCapacity_DateRange" CHECK ("EffectiveTo" IS NULL OR "EffectiveTo" >= "EffectiveFrom"),
    CONSTRAINT "CK_Rec_EmployeeCapacity_WeeklyCapacityHours" CHECK ("WeeklyCapacityHours" > 0)
);

CREATE INDEX IF NOT EXISTS "IX_Rec_EmployeeCapacity_EmployeeId_EffectiveFrom"
    ON "Rec_EmployeeCapacity" ("EmployeeId", "EffectiveFrom");

-- ---------------------------------------------------------------------
-- Rec_EmployeeLocationEvents
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Rec_EmployeeLocationEvents" (
    "EmployeeLocationEventId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeId"              integer NOT NULL,
    "WorkItemId"              integer NULL,
    "SiteId"                  integer NULL,
    "EventType"               varchar(30)  NOT NULL,
    "InputAddress"            varchar(300) NULL,
    "FormattedAddress"        varchar(300) NULL,
    "ExternalPlaceRef"        varchar(200) NULL,
    "ZoneId"                  integer NULL,
    "EventDate"               date NOT NULL,
    "EventTime"               timestamp(0) NOT NULL,
    "Source"                  varchar(50)  NULL,
    "Notes"                   varchar(500) NULL,
    "CreatedAt"               timestamp(0) NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "FK_Rec_EmployeeLocationEvents_Employees" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("EmployeeId"),
    CONSTRAINT "FK_Rec_EmployeeLocationEvents_Sites" FOREIGN KEY ("SiteId") REFERENCES "Sites" ("SiteId"),
    CONSTRAINT "FK_Rec_EmployeeLocationEvents_WorkItems" FOREIGN KEY ("WorkItemId") REFERENCES "WorkItems" ("WorkItemId"),
    CONSTRAINT "FK_Rec_EmployeeLocationEvents_WorkZones" FOREIGN KEY ("ZoneId") REFERENCES "Rec_WorkZones" ("ZoneId"),
    CONSTRAINT "CK_Rec_EmployeeLocationEvents_EventType" CHECK ("EventType" IN ('WorkCompletion','Manual','SiteVisit','HomeBase'))
);

CREATE INDEX IF NOT EXISTS "IX_Rec_EmployeeLocationEvents_EmployeeId_EventDate_EventTime"
    ON "Rec_EmployeeLocationEvents" ("EmployeeId", "EventDate", "EventTime" DESC);

-- ---------------------------------------------------------------------
-- Rec_EmployeePlannedStops
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Rec_EmployeePlannedStops" (
    "PlannedStopId"    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeId"       integer NOT NULL,
    "WorkItemId"       integer NOT NULL,
    "SiteId"           integer NULL,
    "PlannedDate"      date NOT NULL,
    "PlannedStartAt"   timestamp(0) NULL,
    "PlannedEndAt"     timestamp(0) NULL,
    "InputAddress"     varchar(300) NULL,
    "FormattedAddress" varchar(300) NULL,
    "ExternalPlaceRef" varchar(200) NULL,
    "ZoneId"           integer NULL,
    "StopStatus"       varchar(30)  NOT NULL DEFAULT 'Planned',
    "CreatedAt"        timestamp(0) NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt"        timestamp(0) NULL,
    CONSTRAINT "FK_Rec_EmployeePlannedStops_Employees" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("EmployeeId"),
    CONSTRAINT "FK_Rec_EmployeePlannedStops_Sites" FOREIGN KEY ("SiteId") REFERENCES "Sites" ("SiteId"),
    CONSTRAINT "FK_Rec_EmployeePlannedStops_WorkItems" FOREIGN KEY ("WorkItemId") REFERENCES "WorkItems" ("WorkItemId"),
    CONSTRAINT "FK_Rec_EmployeePlannedStops_WorkZones" FOREIGN KEY ("ZoneId") REFERENCES "Rec_WorkZones" ("ZoneId"),
    CONSTRAINT "CK_Rec_EmployeePlannedStops_StopStatus" CHECK ("StopStatus" IN ('Cancelled','Completed','InProgress','Planned')),
    CONSTRAINT "CK_Rec_EmployeePlannedStops_TimeRange" CHECK ("PlannedStartAt" IS NULL OR "PlannedEndAt" IS NULL OR "PlannedStartAt" <= "PlannedEndAt")
);

CREATE INDEX IF NOT EXISTS "IX_Rec_EmployeePlannedStops_EmployeeId_PlannedDate_PlannedEndAt"
    ON "Rec_EmployeePlannedStops" ("EmployeeId", "PlannedDate", "PlannedEndAt");

-- ---------------------------------------------------------------------
-- Rec_EmployeeSkills
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Rec_EmployeeSkills" (
    "EmployeeSkillId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeId"      integer NOT NULL,
    "SkillId"         integer NOT NULL,
    "SkillLevel"      integer NOT NULL,
    "YearsExperience" numeric(5, 2) NULL,
    "IsCertified"     boolean NOT NULL DEFAULT false,
    "LastUsedAt"      timestamp(0) NULL,
    "Notes"           varchar(500) NULL,
    "CreatedAt"       timestamp(0) NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "UQ_Rec_EmployeeSkills_EmployeeId_SkillId" UNIQUE ("EmployeeId", "SkillId"),
    CONSTRAINT "FK_Rec_EmployeeSkills_Employees" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("EmployeeId"),
    CONSTRAINT "FK_Rec_EmployeeSkills_Skills" FOREIGN KEY ("SkillId") REFERENCES "Rec_Skills" ("SkillId"),
    CONSTRAINT "CK_Rec_EmployeeSkills_SkillLevel" CHECK ("SkillLevel" >= 1 AND "SkillLevel" <= 5),
    CONSTRAINT "CK_Rec_EmployeeSkills_YearsExperience" CHECK ("YearsExperience" IS NULL OR "YearsExperience" >= 0)
);

CREATE INDEX IF NOT EXISTS "IX_Rec_EmployeeSkills_EmployeeId" ON "Rec_EmployeeSkills" ("EmployeeId");
CREATE INDEX IF NOT EXISTS "IX_Rec_EmployeeSkills_SkillId" ON "Rec_EmployeeSkills" ("SkillId");

-- ---------------------------------------------------------------------
-- Rec_EmployeeWorkZones
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Rec_EmployeeWorkZones" (
    "EmployeeWorkZoneId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeId"         integer NOT NULL,
    "ZoneId"             integer NOT NULL,
    "IsPrimary"          boolean NOT NULL DEFAULT false,
    "Notes"              varchar(500) NULL,
    "CreatedAt"          timestamp(0) NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "UQ_Rec_EmployeeWorkZones_EmployeeId_ZoneId" UNIQUE ("EmployeeId", "ZoneId"),
    CONSTRAINT "FK_Rec_EmployeeWorkZones_Employees" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("EmployeeId"),
    CONSTRAINT "FK_Rec_EmployeeWorkZones_WorkZones" FOREIGN KEY ("ZoneId") REFERENCES "Rec_WorkZones" ("ZoneId")
);

-- ---------------------------------------------------------------------
-- Rec_RecommendationRuns
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Rec_RecommendationRuns" (
    "RecommendationRunId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ScopeType"           varchar(30)  NOT NULL,
    "ProjectId"           integer NULL,
    "TaskId"              integer NULL,
    "RequestedByUserId"   integer NULL,
    "AlgorithmVersion"    varchar(50)  NOT NULL DEFAULT '1.0',
    "RunStatus"           varchar(30)  NOT NULL DEFAULT 'Completed',
    "InputSnapshotJson"   text NULL,
    "SummaryJson"         text NULL,
    "CreatedAt"           timestamp(0) NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "FK_Rec_RecommendationRuns_Project_WorkItems" FOREIGN KEY ("ProjectId") REFERENCES "WorkItems" ("WorkItemId"),
    CONSTRAINT "FK_Rec_RecommendationRuns_Task_WorkItems" FOREIGN KEY ("TaskId") REFERENCES "WorkItems" ("WorkItemId"),
    CONSTRAINT "FK_Rec_RecommendationRuns_Users" FOREIGN KEY ("RequestedByUserId") REFERENCES "Users" ("UserId"),
    CONSTRAINT "CK_Rec_RecommendationRuns_RunStatus" CHECK ("RunStatus" IN ('Partial','Failed','Completed')),
    CONSTRAINT "CK_Rec_RecommendationRuns_ScopeType" CHECK ("ScopeType" IN ('AllProjects','Task','Project'))
);

CREATE INDEX IF NOT EXISTS "IX_Rec_RecommendationRuns_ProjectId_CreatedAt"
    ON "Rec_RecommendationRuns" ("ProjectId", "CreatedAt" DESC);

-- ---------------------------------------------------------------------
-- Rec_RouteEstimates
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Rec_RouteEstimates" (
    "RouteEstimateId"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeId"             integer NOT NULL,
    "TargetSiteId"           integer NOT NULL,
    "OriginType"             varchar(30)  NOT NULL,
    "OriginReferenceId"      integer NULL,
    "OriginAddress"          varchar(300) NULL,
    "TargetAddress"          varchar(300) NULL,
    "RoutingProvider"        varchar(50)  NULL,
    "RoutingStatus"          varchar(30)  NULL,
    "RoutingMode"            varchar(20)  NOT NULL DEFAULT 'Driving',
    "EstimatedDistanceKm"    numeric(10, 2) NULL,
    "EstimatedTravelMinutes" integer NULL,
    "CalculatedAt"           timestamp(0) NOT NULL DEFAULT (now() at time zone 'utc'),
    "IsCurrent"              boolean NOT NULL DEFAULT true,
    CONSTRAINT "FK_Rec_RouteEstimates_Employees" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("EmployeeId"),
    CONSTRAINT "FK_Rec_RouteEstimates_Sites" FOREIGN KEY ("TargetSiteId") REFERENCES "Sites" ("SiteId"),
    CONSTRAINT "CK_Rec_RouteEstimates_Distance" CHECK ("EstimatedDistanceKm" IS NULL OR "EstimatedDistanceKm" >= 0),
    CONSTRAINT "CK_Rec_RouteEstimates_OriginType" CHECK ("OriginType" IN ('PlannedStop','LastKnownLocation','HomeBase')),
    CONSTRAINT "CK_Rec_RouteEstimates_RoutingMode" CHECK ("RoutingMode" IN ('Cycling','Walking','Driving')),
    CONSTRAINT "CK_Rec_RouteEstimates_TravelMinutes" CHECK ("EstimatedTravelMinutes" IS NULL OR "EstimatedTravelMinutes" >= 0)
);

CREATE INDEX IF NOT EXISTS "IX_Rec_RouteEstimates_EmployeeId_TargetSiteId_Current"
    ON "Rec_RouteEstimates" ("EmployeeId", "TargetSiteId", "IsCurrent");

-- ---------------------------------------------------------------------
-- Rec_SiteAddressProfile
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Rec_SiteAddressProfile" (
    "SiteAddressProfileId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SiteId"               integer NOT NULL,
    "InputAddress"         varchar(300) NULL,
    "FormattedAddress"     varchar(300) NULL,
    "ValidationProvider"   varchar(50)  NULL,
    "ValidationStatus"     varchar(30)  NULL,
    "ValidationVerdict"    varchar(50)  NULL,
    "ValidationScore"      numeric(5, 2) NULL,
    "ExternalPlaceRef"     varchar(200) NULL,
    "Street"               varchar(200) NULL,
    "HouseNumber"          varchar(50)  NULL,
    "City"                 varchar(100) NULL,
    "Postcode"             varchar(30)  NULL,
    "StateOrRegion"        varchar(100) NULL,
    "Country"              varchar(100) NULL,
    "ZoneId"               integer NULL,
    "ValidatedAt"          timestamp(0) NULL,
    "CreatedAt"            timestamp(0) NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt"            timestamp(0) NULL,
    CONSTRAINT "UQ_Rec_SiteAddressProfile_SiteId" UNIQUE ("SiteId"),
    CONSTRAINT "FK_Rec_SiteAddressProfile_Sites" FOREIGN KEY ("SiteId") REFERENCES "Sites" ("SiteId"),
    CONSTRAINT "FK_Rec_SiteAddressProfile_WorkZones" FOREIGN KEY ("ZoneId") REFERENCES "Rec_WorkZones" ("ZoneId"),
    CONSTRAINT "CK_Rec_SiteAddressProfile_ValidationScore" CHECK ("ValidationScore" IS NULL OR ("ValidationScore" >= 0 AND "ValidationScore" <= 100))
);

-- ---------------------------------------------------------------------
-- Rec_TaskAssignmentRecommendations
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Rec_TaskAssignmentRecommendations" (
    "RecommendationId"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RecommendationRunId"      integer NOT NULL,
    "TaskId"                   integer NOT NULL,
    "EmployeeId"               integer NOT NULL,
    "UrgencyClass"             varchar(20)  NULL,
    "OriginTypeUsed"           varchar(30)  NULL,
    "RankOrder"                integer NOT NULL,
    "TotalScore"               numeric(10, 2) NOT NULL,
    "ProfessionalScore"        numeric(10, 2) NULL,
    "AvailabilityScore"        numeric(10, 2) NULL,
    "WorkloadScore"            numeric(10, 2) NULL,
    "ExperienceScore"          numeric(10, 2) NULL,
    "GeographicScore"          numeric(10, 2) NULL,
    "ContinuityScore"          numeric(10, 2) NULL,
    "DistanceKm"               numeric(10, 2) NULL,
    "TravelMinutes"            integer NULL,
    "MatchedSkillsCount"       integer NULL,
    "MissingSkillsCount"       integer NULL,
    "OpenAssignmentsCount"     integer NULL,
    "CurrentWorkloadHours"     numeric(10, 2) NULL,
    "ZoneMatch"                boolean NULL,
    "WorkedWithCustomerBefore" boolean NULL,
    "WorkedAtSiteBefore"       boolean NULL,
    "RecommendationSummary"    varchar(1000) NULL,
    "WarningsJson"             text NULL,
    "CreatedAt"                timestamp(0) NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "UQ_Rec_TaskAssignmentRecommendations_Run_Task_Employee" UNIQUE ("RecommendationRunId", "TaskId", "EmployeeId"),
    CONSTRAINT "FK_Rec_TaskAssignmentRecommendations_Runs" FOREIGN KEY ("RecommendationRunId") REFERENCES "Rec_RecommendationRuns" ("RecommendationRunId"),
    CONSTRAINT "FK_Rec_TaskAssignmentRecommendations_WorkItems" FOREIGN KEY ("TaskId") REFERENCES "WorkItems" ("WorkItemId"),
    CONSTRAINT "FK_Rec_TaskAssignmentRecommendations_Employees" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("EmployeeId"),
    CONSTRAINT "CK_Rec_TaskAssignmentRecommendations_OriginTypeUsed" CHECK ("OriginTypeUsed" IS NULL OR "OriginTypeUsed" IN ('PlannedStop','LastKnownLocation','HomeBase')),
    CONSTRAINT "CK_Rec_TaskAssignmentRecommendations_RankOrder" CHECK ("RankOrder" >= 1),
    CONSTRAINT "CK_Rec_TaskAssignmentRecommendations_TotalScore" CHECK ("TotalScore" >= 0),
    CONSTRAINT "CK_Rec_TaskAssignmentRecommendations_UrgencyClass" CHECK ("UrgencyClass" IS NULL OR "UrgencyClass" IN ('Critical','Urgent','Normal','Low'))
);

CREATE INDEX IF NOT EXISTS "IX_Rec_TaskAssignmentRecommendations_Run_Task_Rank"
    ON "Rec_TaskAssignmentRecommendations" ("RecommendationRunId", "TaskId", "RankOrder");

-- ---------------------------------------------------------------------
-- Rec_WorkItemAlgorithmProfile
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Rec_WorkItemAlgorithmProfile" (
    "WorkItemAlgorithmProfileId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "WorkItemId"                 integer NOT NULL,
    "ProjectType"                varchar(100) NULL,
    "RequiredWorkersCount"       integer NOT NULL DEFAULT 1,
    "AlgorithmPriorityOverride"  varchar(20)  NULL,
    "UrgencyOverride"            varchar(20)  NULL,
    "PlanningNotes"              varchar(500) NULL,
    "CreatedAt"                  timestamp(0) NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt"                  timestamp(0) NULL,
    CONSTRAINT "UQ_Rec_WorkItemAlgorithmProfile_WorkItemId" UNIQUE ("WorkItemId"),
    CONSTRAINT "FK_Rec_WorkItemAlgorithmProfile_WorkItems" FOREIGN KEY ("WorkItemId") REFERENCES "WorkItems" ("WorkItemId"),
    CONSTRAINT "CK_Rec_WorkItemAlgorithmProfile_AlgorithmPriorityOverride" CHECK ("AlgorithmPriorityOverride" IS NULL OR "AlgorithmPriorityOverride" IN ('Critical','High','Medium','Low')),
    CONSTRAINT "CK_Rec_WorkItemAlgorithmProfile_RequiredWorkersCount" CHECK ("RequiredWorkersCount" >= 1),
    CONSTRAINT "CK_Rec_WorkItemAlgorithmProfile_UrgencyOverride" CHECK ("UrgencyOverride" IS NULL OR "UrgencyOverride" IN ('Critical','Urgent','Normal','Low'))
);

CREATE INDEX IF NOT EXISTS "IX_Rec_WorkItemAlgorithmProfile_WorkItemId"
    ON "Rec_WorkItemAlgorithmProfile" ("WorkItemId");

-- ---------------------------------------------------------------------
-- Rec_WorkItemRequiredSkills
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Rec_WorkItemRequiredSkills" (
    "WorkItemRequiredSkillId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "WorkItemId"              integer NOT NULL,
    "SkillId"                 integer NOT NULL,
    "RequiredLevel"           integer NULL,
    "ImportanceLevel"         varchar(20)  NOT NULL DEFAULT 'Preferred',
    "Notes"                   varchar(500) NULL,
    "CreatedAt"               timestamp(0) NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "UQ_Rec_WorkItemRequiredSkills_WorkItemId_SkillId" UNIQUE ("WorkItemId", "SkillId"),
    CONSTRAINT "FK_Rec_WorkItemRequiredSkills_WorkItems" FOREIGN KEY ("WorkItemId") REFERENCES "WorkItems" ("WorkItemId"),
    CONSTRAINT "FK_Rec_WorkItemRequiredSkills_Skills" FOREIGN KEY ("SkillId") REFERENCES "Rec_Skills" ("SkillId"),
    CONSTRAINT "CK_Rec_WorkItemRequiredSkills_ImportanceLevel" CHECK ("ImportanceLevel" IN ('Preferred','Important','Critical')),
    CONSTRAINT "CK_Rec_WorkItemRequiredSkills_RequiredLevel" CHECK ("RequiredLevel" IS NULL OR ("RequiredLevel" >= 1 AND "RequiredLevel" <= 5))
);

CREATE INDEX IF NOT EXISTS "IX_Rec_WorkItemRequiredSkills_WorkItemId"
    ON "Rec_WorkItemRequiredSkills" ("WorkItemId");
